[package]
name = "RustWebservice"
version = "0.1.0"
edition = "2024"
authors = ["Sunnickel"]
categories = ["web-programming::http-server"]


[dependencies]
chrono = "0.4.42"
log = "0.4.28"
rustls = "0.21"
rustls-pemfile = "1.0"
time = "0.3.44"
